directories:
  output: release
  buildResources: build
appId: com.sistetecni.lavanderia
productName: Lavanderia y Sastreria Sistetecni
files:
  - filter:
      - dist/**
      - dist-electron/**
      - package.json
extraResources:
  - from: resources/bin
    to: bin
publish:
  - provider: github
    owner: santiagomontanes
    repo: lavanderia-sastreria
    releaseType: release
win:
  target:
    - nsis
mac:
  category: public.app-category.business
  target:
    - dmg
    - zip
linux:
  category: Office
  target:
    - AppImage
    - deb
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 35.7.5
